events {}

http {

    upstream event_service {
        server event-service:8080;
    }

    upstream ticket_service {
        server ticket-service:8081;
    }

    server {

        listen 80;

        location /events/ {
            proxy_pass http://event_service;
        }

        location /tickets/ {
            proxy_pass http://ticket_service;
        }
    }
}